; M5Stack Cardputer ADV 摩斯电码学习器
; 全部文件在 D 盘，不占用 C 盘空间
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_build.f_flash = 80000000L

lib_deps =
    m5stack/M5Cardputer@^1.1.0
    m5stack/M5Unified@^0.2.0
